CREATE TABLE `issue_pr_event` (
  `event_idx` int NOT NULL AUTO_INCREMENT,
  `event` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `author` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `author_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `email` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `author_type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `author_association` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `commit_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `repo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `type` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `state` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `assignees` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `body` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `submitted_at` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `links` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `old_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `new_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `requester` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `reviewer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `dismissed_state` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `dismissal_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `repo_id` int NOT NULL,
  `repo_source` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issue_number` int NOT NULL,
  `issue_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `issue_status` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`event_idx`),
  UNIQUE KEY `event_idx_UNIQUE` (`event_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
